spring.application.name=clyvoHelper
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL
spring.datasource.username=rm566230
spring.datasource.password=210803
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cache.type=simple

server.port=8080
openrouter.api.key=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